spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hubsaude?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: zero81
    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#      path: "/h2"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never

api.security.token: ${JWT_SECRET:fDJLGpzWaltcQexKkMxTaw}